version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: picobrain-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: picobraindb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: picobrain-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/picobraindb
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

volumes:
  postgres-data: