databases:
  - name: picobraindb
    databaseName: picobraindb
    user: picobrain
    region: oregon
    plan: starter

services:
  - type: web
    name: picobrain-api
    runtime: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: picobraindb
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true